### ISSUE TITLE
jessie version 

### ISSUE THREAD

**Issue by arthurlogilab** [ikatson/docker-reviewboard#10] opened 2016-10-05 12:35 UTC
would it be possible to have a jessie version of docker-reviewboard ?

**Comment by ikatson** [comment] 2016-10-18 05:00
Hi, I tried to assemble this one jessie, but because of various bugs during installation, decided to go with RPM packages from centos, as the official installation guide suggests.

I merged this one today https://github.com/ikatson/docker-reviewboard/pull/12, which made the dockerfile actually work, and make it smaller and simpler.

Please consider using this instead of jessie.

**Closed by ikatson** 2016-10-18 05:00 UTC

**Comment by arthurlogilab** [comment] 2016-10-18 14:16
I do prefer having a debian/jessie under the hood, but if reviewboard is better supported under centos I understand your choice (if I end up using this I can contribute a Dockerfile.debian) 

For now it's not working with my centos:7 image (build from ```sudo /usr/share/docker-engine/contrib/mkimage.sh -t centos:7 rinse --distribution centos-7```  with docker-engine ```1.12.2-0~xenial```



```
$ docker build -t ikatson/reviewboard .
Sending build context to Docker daemon   107 kB
Step 1 : FROM centos:7
 ---> 6a56676ea5c3
Step 2 : MAINTAINER igor.katson@gmail.com
 ---> Using cache
 ---> 3c20f31eb4a3
Step 3 : RUN yum install -y epel-release &&     yum install -y ReviewBoard-2.5.6.1 uwsgi RBTools       uwsgi-plugin-python python-ldap python-pip python2-boto &&     yum clean all
 ---> Running in 3ddcae3dbb1f
Loaded plugins: fastestmirror, keys, protectbase
Loading mirror speeds from cached hostfile
 * base: centos.crazyfrogs.org
 * extras: centos.trisect.eu
 * updates: centos.mirror.fr.planethoster.net
0 packages excluded due to repository protections
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                Arch             Version         Repository        Size
================================================================================
Installing:
 epel-release           noarch           7-6             extras            14 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 14 k
Installed size: 24 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : epel-release-7-6.noarch                                      1/1 
  Verifying  : epel-release-7-6.noarch                                      1/1 

Installed:
  epel-release.noarch 0:7-6                                                     

Complete!
Loaded plugins: fastestmirror, keys, protectbase
Loading mirror speeds from cached hostfile
 * base: centos.crazyfrogs.org
 * epel: mirrors.ircam.fr
 * extras: centos.trisect.eu
 * updates: centos.mirror.fr.planethoster.net
Error: xz compression not available
The command '/bin/sh -c yum install -y epel-release &&     yum install -y ReviewBoard-2.5.6.1 uwsgi RBTools       uwsgi-plugin-python python-ldap python-pip python2-boto &&     yum clean all' returned a non-zero code: 1
```

Any ideas ?

**Comment by ikatson** [comment] 2016-10-18 14:41
The solution would be to install the "xz" or maybe "xz-libs" package, but why don't you just download the upstream centos image? Just "docker pull centos:7" works for me, and this repo builds fine in it

**Comment by arthurlogilab** [comment] 2016-10-18 15:00
I'm not a big fan of pulling massive binary blobs from the internet and running them on my machine (see history on https://securityblog.redhat.com/2014/12/18/before-you-initiate-a-docker-pull/ although it has improved). I thrust rinse & deboostrap more than binary blobs. This is why I'm using the mkimage.sh shipped with docker-engine. 

can't seem to solve my issue with install of xz or xz-libs or removing the cache as some search on centos seems to suggest.

**Comment by ikatson** [comment] 2016-10-18 16:08
Just double-checking, did you try installing those before the "RUN yum install..." command?

I.e. modifying the dockerfile, so that "RUN yum install -y xz xz-libs" line goes right after "MAINTAINER"?

It takes time to reproduce your issue, as I'm building on OSX and none of those tools you use are available

**Comment by arthurlogilab** [comment] 2016-10-18 16:43
yes. I did put the yum install just after MAINTAINER.

Thanks for looking at this.

**Comment by ikatson** [comment] 2016-10-18 17:47
I fixed it for you in master

**Comment by ikatson** [comment] 2016-10-20 16:14
@arthurlogilab, did it help?

**Comment by arthurlogilab** [comment] 2016-11-02 09:39
@ikatson yeah! it looks good. Thanks a bunch.
